export const PROPERTIES_LOADING = "PROPERTIES_LOADING";
export const PROPERTIES_CREATE = "PROPERTIES_CREATE";
export const PROPERTIES_LOAD = "PROPERTIES_LOAD";
export const PROPERTIE_LOAD = "PROPERTIE_LOAD";
export const PROPERTIES_USER = "PROPERTIES_USER";
export const PROPERTIE_DELETE = "PROPERTIE_DELETE";
export const PROPERTIES_FAIL = "PROPERTIES_FAIL";
