export const SUBSCRIPTIONS_LOADING = "SUBSCRIPTIONS_LOADING";
export const SUBSCRIPTIONS_LOAD = "SUBSCRIPTIONS_LOAD";
export const SUBSCRIPTION_LOAD = "SUBSCRIPTION_LOAD";
export const SUBSCRIPTIONS_FAIL = "SUBSCRIPTIONS_FAIL";
