export const months = [
  "Jan",
  "Feb",
  "Mar",
  "Apr",
  "May",
  "Jun",
  "Jul",
  "Aug",
  "Sept",
  "Oct",
  "Nov",
  "Dec",
];

export const schedules = [
  { value: 0, label: "12:00 am" },
  { value: 1, label: "01:00 am" },
  { value: 2, label: "02:00 am" },
  { value: 3, label: "03:00 am" },
  { value: 4, label: "04:00 am" },
  { value: 5, label: "05:00 am" },
  { value: 6, label: "06:00 am" },
  { value: 7, label: "07:00 am" },
  { value: 8, label: "08:00 am" },
  { value: 9, label: "09:00 am" },
  { value: 10, label: "10:00 am" },
  { value: 11, label: "11:00 am" },
  { value: 12, label: "12:00 pm" },
  { value: 13, label: "01:00 pm" },
  { value: 14, label: "02:00 pm" },
  { value: 15, label: "03:00 pm" },
  { value: 16, label: "04:00 pm" },
  { value: 17, label: "05:00 pm" },
  { value: 18, label: "06:00 pm" },
  { value: 19, label: "07:00 pm" },
  { value: 20, label: "08:00 pm" },
  { value: 21, label: "09:00 pm" },
  { value: 22, label: "10:00 pm" },
  { value: 23, label: "11:00 pm" },
];

export const weekDays = [
  { value: 0, label: "Domingo" },
  { value: 1, label: "Lunes" },
  { value: 2, label: "Martes" },
  { value: 3, label: "Miércoles" },
  { value: 4, label: "Jueves" },
  { value: 5, label: "Viernes" },
  { value: 6, label: "Sábado" },
];

export const monthNames = [
  { value: 1, label: "Enero" },
  { value: 2, label: "Febrero" },
  { value: 3, label: "Marzo" },
  { value: 4, label: "Abril" },
  { value: 5, label: "Mayo" },
  { value: 6, label: "Junio" },
  { value: 7, label: "Julio" },
  { value: 8, label: "Agosto" },
  { value: 9, label: "Septiembre" },
  { value: 10, label: "Octubre" },
  { value: 11, label: "Noviembre" },
  { value: 12, label: "Diciembre" },
];
