export const CATEGORIES_LOADING = "CATEGORIES_LOADING";
export const CATEGORIES_CREATE = "CATEGORIES_CREATE";
export const CATEGORIES_LOAD = "CATEGORIES_LOAD";
export const CATEGORIE_LOAD = "CATEGORIE_LOAD";
export const CATEGORIE_DELETE = "CATEGORIE_DELETE";
export const CATEGORIES_FAIL = "CATEGORIES_FAIL";
